name: Build Docker image

on:
push:
branches:
- main 

jobs:
build:
runs-on: ubuntu-lastest

steps:
- name: Checkout Repo
uses: actions/checkout@v3

- name: Set up Docker
uses: docker/setup-buildx-action@v2

- name: Build Docker image
run: docker build -t ashwin-micro-app .